# Generated by Django 5.1.6 on 2025-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_category_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sample_file',
            field=models.FileField(blank=True, null=True, upload_to='samples/'),
        ),
    ]
